//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.RecuitSimule {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.RecuitSimule.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à import ctypes
        ///
        ///import numpy as np
        ///
        ///import clr 
        ///import System
        ///from System import Array, Int32
        ///from System.Runtime.InteropServices import GCHandle, GCHandleType
        ///
        ///_MAP_NP_NET = {
        ///    np.dtype(np.float32): System.Single,
        ///    np.dtype(np.float64): System.Double,
        ///    np.dtype(np.int8)   : System.SByte,
        ///    np.dtype(np.int16)  : System.Int16,
        ///    np.dtype(np.int32)  : System.Int32,
        ///    np.dtype(np.int64)  : System.Int64,
        ///    np.dtype(np.uint8)  : System.Byte,
        ///    np.dtype(np.uint16) : System.UInt1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Numpy_convert {
            get {
                return ResourceManager.GetString("Numpy_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à import random
        ///import numpy 
        ///import math 
        ///from random import choice
        ///import statistics 
        ///
        ///
        ///sudoku = numpy.asarray(sudokud)
        ///def PrintSudoku(sudoku):
        ///    print(&quot;\n&quot;)
        ///    for i in range(len(sudoku)):
        ///        line = &quot;&quot;
        ///        if i == 3 or i == 6:
        ///            print(&quot;---------------------&quot;)
        ///        for j in range(len(sudoku[i])):
        ///            if j == 3 or j == 6:
        ///                line += &quot;| &quot;
        ///            line += str(sudoku[i,j])+&quot; &quot;
        ///        print(line)
        ///
        ///def FixSudokuValues(fixed_sudoku):
        ///    for  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string RecuitSimule {
            get {
                return ResourceManager.GetString("RecuitSimule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à import copy
        ///import random
        ///import numpy as np
        ///from simanneal import Annealer
        ///
        ///sudoku = np.asarray(sudokud)
        ///
        ///# from https://neos-guide.org/content/sudoku
        ///#_ = 0
        ///#PROBLEM = np.array([
        ///#    1, _, _,  _, _, 6,  3, _, 8,
        ///#    _, _, 2,  3, _, _,  _, 9, _,
        ///#    _, _, _,  _, _, _,  7, 1, 6,
        ///
        ///#    7, _, 8,  9, 4, _,  _, _, 2,
        ///#    _, _, 4,  _, _, _,  9, _, _,
        ///#    9, _, _,  _, 2, 5,  1, _, 4,
        ///
        ///#    6, 2, 9,  _, _, _,  _, _, _,
        ///#    _, 4, _,  _, _, 7,  6, _, _,
        ///#    5, _, 7,  6, _, _,  _, _, 3,
        ///#] [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Simanneal {
            get {
                return ResourceManager.GetString("Simanneal", resourceCulture);
            }
        }
    }
}
